# Collection of example negotiation scenarios
# Each demonstrates different aspects of the negotiation simulator

---
# ===== BUSINESS SCENARIOS =====

# Merger & Acquisition Negotiation
merger_acquisition:
  name: "Tech Company Acquisition"
  description: "Negotiation between acquiring company and target startup"

  entities:
    - name: "AcquiringCorp"
      type: "company"
      utility:
        weights:
          price: 0.4
          equity_stake: 0.3
          earnout_period: 0.2
          retention_bonus: 0.1
        ideal_values:
          price: 50  # $50M
          equity_stake: 100  # 100% ownership
          earnout_period: 12  # 12 months
          retention_bonus: 5  # $5M
        reservation_values:
          price: 150  # Max $150M
          equity_stake: 51  # Min 51% control
          earnout_period: 36  # Max 36 months
          retention_bonus: 20  # Max $20M
      policy:
        type: "boulware"
        params:
          accept_threshold: 0.7
          initial_demand: 0.95
          concession_rate: 0.04
          patience: 40
          stubbornness: 0.8

    - name: "TargetStartup"
      type: "company"
      utility:
        weights:
          price: 0.5
          equity_stake: 0.2
          earnout_period: 0.1
          retention_bonus: 0.2
        ideal_values:
          price: 200  # Want $200M
          equity_stake: 30  # Keep 30% stake
          earnout_period: 6  # Short earnout
          retention_bonus: 25  # $25M retention
        reservation_values:
          price: 75  # Min $75M
          equity_stake: 85  # Max 85% sale
          earnout_period: 24  # Max 24 months
          retention_bonus: 10  # Min $10M
      policy:
        type: "adaptive"
        params:
          accept_threshold: 0.65
          initial_demand: 0.9
          learning_rate: 0.15
          exploration_factor: 0.2

  issues:
    - name: "price"
      min_value: 25
      max_value: 250
      unit: "million_USD"
      divisible: true

    - name: "equity_stake"
      min_value: 0
      max_value: 100
      unit: "percent"
      divisible: true

    - name: "earnout_period"
      min_value: 0
      max_value: 48
      unit: "months"
      divisible: false

    - name: "retention_bonus"
      min_value: 0
      max_value: 30
      unit: "million_USD"
      divisible: true

  max_rounds: 100
  protocol: "alternating"
  track_pareto: true
  calculate_nash: true

---
# Supply Chain Contract Negotiation
supply_chain:
  name: "Manufacturing Supply Agreement"
  description: "Multi-year supply contract between manufacturer and supplier"

  entities:
    - name: "Manufacturer"
      type: "company"
      utility:
        weights:
          unit_price: 0.4
          volume_commitment: 0.2
          delivery_time: 0.2
          quality_guarantee: 0.1
          payment_terms: 0.1
        ideal_values:
          unit_price: 10
          volume_commitment: 100000
          delivery_time: 7
          quality_guarantee: 99.9
          payment_terms: 90
        reservation_values:
          unit_price: 25
          volume_commitment: 50000
          delivery_time: 21
          quality_guarantee: 98
          payment_terms: 30
      policy:
        type: "tit_for_tat"
        params:
          accept_threshold: 0.7
          stubbornness: 0.5

    - name: "Supplier"
      type: "company"
      utility:
        weights:
          unit_price: 0.5
          volume_commitment: 0.2
          delivery_time: 0.1
          quality_guarantee: 0.1
          payment_terms: 0.1
        ideal_values:
          unit_price: 30
          volume_commitment: 200000
          delivery_time: 21
          quality_guarantee: 98
          payment_terms: 15
        reservation_values:
          unit_price: 15
          volume_commitment: 75000
          delivery_time: 7
          quality_guarantee: 99.5
          payment_terms: 60
      policy:
        type: "linear_concession"
        params:
          accept_threshold: 0.65
          concession_rate: 0.08

  issues:
    - name: "unit_price"
      min_value: 5
      max_value: 35
      unit: "USD"
      divisible: true

    - name: "volume_commitment"
      min_value: 25000
      max_value: 250000
      unit: "units_per_year"
      divisible: false

    - name: "delivery_time"
      min_value: 3
      max_value: 30
      unit: "days"
      divisible: false

    - name: "quality_guarantee"
      min_value: 95
      max_value: 99.99
      unit: "percent"
      divisible: true

    - name: "payment_terms"
      min_value: 0
      max_value: 120
      unit: "days"
      divisible: false

  max_rounds: 75
  protocol: "alternating"

---
# ===== INTERNATIONAL RELATIONS =====

# Trade Agreement
trade_agreement:
  name: "Bilateral Trade Agreement"
  description: "Trade negotiations between two countries"

  entities:
    - name: "DevelopedNation"
      type: "country"
      utility:
        weights:
          tariff_reduction: 0.3
          market_access: 0.3
          ip_protection: 0.2
          labor_standards: 0.1
          environmental_standards: 0.1
        ideal_values:
          tariff_reduction: 50
          market_access: 100
          ip_protection: 100
          labor_standards: 50
          environmental_standards: 50
        reservation_values:
          tariff_reduction: 20
          market_access: 60
          ip_protection: 70
          labor_standards: 30
          environmental_standards: 30
      policy:
        type: "boulware"
        params:
          accept_threshold: 0.75
          patience: 50

    - name: "DevelopingNation"
      type: "country"
      utility:
        weights:
          tariff_reduction: 0.4
          market_access: 0.4
          ip_protection: 0.1
          labor_standards: 0.05
          environmental_standards: 0.05
        ideal_values:
          tariff_reduction: 80
          market_access: 100
          ip_protection: 40
          labor_standards: 30
          environmental_standards: 30
        reservation_values:
          tariff_reduction: 30
          market_access: 70
          ip_protection: 60
          labor_standards: 50
          environmental_standards: 50
      policy:
        type: "conceder"
        params:
          accept_threshold: 0.6
          concession_rate: 0.1

  issues:
    - name: "tariff_reduction"
      min_value: 0
      max_value: 100
      unit: "percent"

    - name: "market_access"
      min_value: 0
      max_value: 100
      unit: "percent"

    - name: "ip_protection"
      min_value: 0
      max_value: 100
      unit: "score"

    - name: "labor_standards"
      min_value: 0
      max_value: 100
      unit: "score"

    - name: "environmental_standards"
      min_value: 0
      max_value: 100
      unit: "score"

  max_rounds: 150
  protocol: "alternating"

---
# Climate Summit
climate_summit:
  name: "Global Climate Summit 2025"
  description: "Multi-party climate negotiations"

  entities:
    - name: "USA"
      type: "country"
      utility:
        weights:
          emissions_reduction: 0.25
          financial_contribution: 0.25
          technology_transfer: 0.25
          timeline: 0.25
        ideal_values:
          emissions_reduction: 30
          financial_contribution: 20
          technology_transfer: 60
          timeline: 2040
        reservation_values:
          emissions_reduction: 45
          financial_contribution: 50
          technology_transfer: 40
          timeline: 2030
      policy:
        type: "mixed"
        params:
          accept_threshold: 0.7

    - name: "China"
      type: "country"
      utility:
        weights:
          emissions_reduction: 0.2
          financial_contribution: 0.1
          technology_transfer: 0.5
          timeline: 0.2
        ideal_values:
          emissions_reduction: 20
          financial_contribution: 5
          technology_transfer: 100
          timeline: 2045
        reservation_values:
          emissions_reduction: 35
          financial_contribution: 15
          technology_transfer: 70
          timeline: 2035
      policy:
        type: "adaptive"
        params:
          accept_threshold: 0.65
          learning_rate: 0.2

    - name: "EU"
      type: "country"
      utility:
        weights:
          emissions_reduction: 0.4
          financial_contribution: 0.2
          technology_transfer: 0.2
          timeline: 0.2
        ideal_values:
          emissions_reduction: 55
          financial_contribution: 40
          technology_transfer: 80
          timeline: 2030
        reservation_values:
          emissions_reduction: 40
          financial_contribution: 60
          technology_transfer: 60
          timeline: 2035
      policy:
        type: "linear_concession"
        params:
          accept_threshold: 0.7
          concession_rate: 0.06

    - name: "India"
      type: "country"
      utility:
        weights:
          emissions_reduction: 0.15
          financial_contribution: 0.35
          technology_transfer: 0.35
          timeline: 0.15
        ideal_values:
          emissions_reduction: 15
          financial_contribution: 100
          technology_transfer: 100
          timeline: 2050
        reservation_values:
          emissions_reduction: 30
          financial_contribution: 50
          technology_transfer: 60
          timeline: 2040
      policy:
        type: "conceder"
        params:
          accept_threshold: 0.6
          concession_rate: 0.1

    - name: "Brazil"
      type: "country"
      utility:
        weights:
          emissions_reduction: 0.2
          financial_contribution: 0.4
          technology_transfer: 0.3
          timeline: 0.1
        ideal_values:
          emissions_reduction: 25
          financial_contribution: 80
          technology_transfer: 90
          timeline: 2045
        reservation_values:
          emissions_reduction: 40
          financial_contribution: 40
          technology_transfer: 50
          timeline: 2035
      policy:
        type: "tit_for_tat"
        params:
          accept_threshold: 0.65

  issues:
    - name: "emissions_reduction"
      min_value: 0
      max_value: 80
      unit: "percent_from_baseline"
      divisible: true

    - name: "financial_contribution"
      min_value: 0
      max_value: 150
      unit: "billion_USD_per_year"
      divisible: true

    - name: "technology_transfer"
      min_value: 0
      max_value: 100
      unit: "percent_of_patents"
      divisible: true

    - name: "timeline"
      min_value: 2025
      max_value: 2050
      unit: "year"
      divisible: false

  max_rounds: 200
  protocol: "simultaneous"
  allow_coalition: true

---
# ===== LABOR NEGOTIATIONS =====

union_negotiation:
  name: "Union Contract Negotiation"
  description: "Labor union negotiating with company management"

  entities:
    - name: "Union"
      type: "organization"
      utility:
        weights:
          wage_increase: 0.4
          healthcare_contribution: 0.2
          vacation_days: 0.15
          remote_work: 0.15
          job_security: 0.1
        ideal_values:
          wage_increase: 15
          healthcare_contribution: 100
          vacation_days: 30
          remote_work: 80
          job_security: 100
        reservation_values:
          wage_increase: 5
          healthcare_contribution: 70
          vacation_days: 20
          remote_work: 40
          job_security: 60
      policy:
        type: "boulware"
        params:
          accept_threshold: 0.7
          patience: 60
          stubbornness: 0.7

    - name: "Management"
      type: "company"
      utility:
        weights:
          wage_increase: 0.35
          healthcare_contribution: 0.25
          vacation_days: 0.1
          remote_work: 0.1
          job_security: 0.2
        ideal_values:
          wage_increase: 2
          healthcare_contribution: 60
          vacation_days: 15
          remote_work: 20
          job_security: 40
        reservation_values:
          wage_increase: 10
          healthcare_contribution: 85
          vacation_days: 25
          remote_work: 60
          job_security: 80
      policy:
        type: "adaptive"
        params:
          accept_threshold: 0.65
          learning_rate: 0.15

  issues:
    - name: "wage_increase"
      min_value: 0
      max_value: 20
      unit: "percent"
      divisible: true

    - name: "healthcare_contribution"
      min_value: 50
      max_value: 100
      unit: "percent_employer_paid"
      divisible: true

    - name: "vacation_days"
      min_value: 10
      max_value: 35
      unit: "days_per_year"
      divisible: false

    - name: "remote_work"
      min_value: 0
      max_value: 100
      unit: "percent_allowed"
      divisible: true

    - name: "job_security"
      min_value: 0
      max_value: 100
      unit: "protection_score"
      divisible: true

  max_rounds: 100
  protocol: "alternating"

---
# ===== RESOURCE ALLOCATION =====

water_rights:
  name: "Regional Water Rights Allocation"
  description: "Multiple stakeholders negotiating water resource allocation"

  entities:
    - name: "Agriculture"
      type: "organization"
      utility:
        weights:
          water_allocation: 0.6
          price_per_unit: 0.3
          priority_rights: 0.1
        ideal_values:
          water_allocation: 60
          price_per_unit: 5
          priority_rights: 100
        reservation_values:
          water_allocation: 35
          price_per_unit: 15
          priority_rights: 50
      policy:
        type: "boulware"
        params:
          accept_threshold: 0.7

    - name: "Urban"
      type: "organization"
      utility:
        weights:
          water_allocation: 0.5
          price_per_unit: 0.2
          priority_rights: 0.3
        ideal_values:
          water_allocation: 40
          price_per_unit: 10
          priority_rights: 100
        reservation_values:
          water_allocation: 25
          price_per_unit: 20
          priority_rights: 60
      policy:
        type: "linear_concession"
        params:
          accept_threshold: 0.65
          concession_rate: 0.08

    - name: "Industry"
      type: "organization"
      utility:
        weights:
          water_allocation: 0.4
          price_per_unit: 0.4
          priority_rights: 0.2
        ideal_values:
          water_allocation: 30
          price_per_unit: 8
          priority_rights: 80
        reservation_values:
          water_allocation: 15
          price_per_unit: 18
          priority_rights: 40
      policy:
        type: "adaptive"
        params:
          accept_threshold: 0.6
          learning_rate: 0.2

    - name: "Environmental"
      type: "organization"
      utility:
        weights:
          water_allocation: 0.7
          price_per_unit: 0.1
          priority_rights: 0.2
        ideal_values:
          water_allocation: 25
          price_per_unit: 0
          priority_rights: 100
        reservation_values:
          water_allocation: 15
          price_per_unit: 10
          priority_rights: 70
      policy:
        type: "fixed_threshold"
        params:
          accept_threshold: 0.75

  issues:
    - name: "water_allocation"
      min_value: 0
      max_value: 100
      unit: "percent_of_total"
      divisible: true

    - name: "price_per_unit"
      min_value: 0
      max_value: 25
      unit: "USD_per_thousand_gallons"
      divisible: true

    - name: "priority_rights"
      min_value: 0
      max_value: 100
      unit: "priority_score"
      divisible: true

  max_rounds: 150
  protocol: "simultaneous"
  allow_coalition: true

---
# ===== REAL ESTATE =====

property_sale:
  name: "Commercial Property Sale"
  description: "Negotiation for commercial real estate transaction"

  entities:
    - name: "Buyer"
      type: "company"
      utility:
        weights:
          price: 0.5
          closing_date: 0.15
          inspection_period: 0.15
          financing_contingency: 0.1
          earnest_money: 0.1
        ideal_values:
          price: 5000000
          closing_date: 90
          inspection_period: 45
          financing_contingency: 60
          earnest_money: 50000
        reservation_values:
          price: 7500000
          closing_date: 30
          inspection_period: 15
          financing_contingency: 30
          earnest_money: 200000
      policy:
        type: "mcts"
        params:
          accept_threshold: 0.7
          simulations: 100

    - name: "Seller"
      type: "company"
      utility:
        weights:
          price: 0.6
          closing_date: 0.1
          inspection_period: 0.1
          financing_contingency: 0.1
          earnest_money: 0.1
        ideal_values:
          price: 8000000
          closing_date: 30
          inspection_period: 10
          financing_contingency: 0
          earnest_money: 250000
        reservation_values:
          price: 6000000
          closing_date: 120
          inspection_period: 30
          financing_contingency: 45
          earnest_money: 100000
      policy:
        type: "q_learning"
        params:
          accept_threshold: 0.65
          alpha: 0.1
          gamma: 0.9
          epsilon: 0.1

  issues:
    - name: "price"
      min_value: 4000000
      max_value: 9000000
      unit: "USD"
      divisible: true

    - name: "closing_date"
      min_value: 15
      max_value: 120
      unit: "days"
      divisible: false

    - name: "inspection_period"
      min_value: 7
      max_value: 60
      unit: "days"
      divisible: false

    - name: "financing_contingency"
      min_value: 0
      max_value: 90
      unit: "days"
      divisible: false

    - name: "earnest_money"
      min_value: 25000
      max_value: 500000
      unit: "USD"
      divisible: true

  max_rounds: 75
  protocol: "alternating"

---
# ===== RESEARCH COLLABORATION =====

research_partnership:
  name: "University-Industry Research Partnership"
  description: "Negotiating terms for joint research project"

  entities:
    - name: "University"
      type: "organization"
      utility:
        weights:
          funding: 0.3
          ip_ownership: 0.3
          publication_rights: 0.2
          student_involvement: 0.2
        ideal_values:
          funding: 5000000
          ip_ownership: 50
          publication_rights: 100
          student_involvement: 100
        reservation_values:
          funding: 2000000
          ip_ownership: 25
          publication_rights: 60
          student_involvement: 50
      policy:
        type: "linear_concession"
        params:
          accept_threshold: 0.65
          concession_rate: 0.07

    - name: "TechCompany"
      type: "company"
      utility:
        weights:
          funding: 0.2
          ip_ownership: 0.5
          publication_rights: 0.2
          student_involvement: 0.1
        ideal_values:
          funding: 1000000
          ip_ownership: 100
          publication_rights: 20
          student_involvement: 30
        reservation_values:
          funding: 3500000
          ip_ownership: 60
          publication_rights: 50
          student_involvement: 70
      policy:
        type: "adaptive"
        params:
          accept_threshold: 0.7
          learning_rate: 0.15

  issues:
    - name: "funding"
      min_value: 500000
      max_value: 6000000
      unit: "USD"
      divisible: true

    - name: "ip_ownership"
      min_value: 0
      max_value: 100
      unit: "percent_company"
      divisible: true

    - name: "publication_rights"
      min_value: 0
      max_value: 100
      unit: "percent_open"
      divisible: true

    - name: "student_involvement"
      min_value: 0
      max_value: 100
      unit: "percent_participation"
      divisible: true

  max_rounds: 80
  protocol: "alternating"
